### ISSUE TITLE
Questions about reproducing training and evaluation results

### ISSUE THREAD

**Issue by yuerbujin** [dyson-ai/hdp#3]
hello, @Yusufma03. Thanks for the source code. I'm facing the some problems when reproducing training and evaluation code.

Question 1: The article says it needs to train for 100k iterations, but when I reproduced it, I found that it seemed to have converged around 1k iterations. I'm not sure if this result is normal, or if you could share the situation of your loss convergence, or could you publish the checkpoint you trained?

<img width="1621" alt="image" src="https://github.com/dyson-ai/hdp/assets/68276188/79bcee82-90ea-4f08-bf3b-268000634e18">

Question 2: When I use my own trained checkpoint for evaluation, I find the results are poor. So, I think there was a problem during my training, but I don't know how to fix it.

<img width="514" alt="image" src="https://github.com/dyson-ai/hdp/assets/68276188/3f765242-fb27-44b8-8938-740cf6de9b14">

<img width="411" alt="image" src="https://github.com/dyson-ai/hdp/assets/68276188/907b9636-969b-473f-9c7f-11d14829134e">

**Comment by Yusufma03** [comment]
Hi, thanks for your interest. The loss for the first step is extremely high as the network has just been initialized. Please set the minimum value of X to greater than 1, and you will see the loss decreasing. To evaluate with your high-level policy, please train your agent with demo augmentation as stated in the appendix A.2. You could enable that by setting `env.demo_aug_ratio` to be greater than 0, and tune the `env.demo_aug_min_len` parameter. This is because PerAct might produce `next_best_poses` that fall short.

Also, the official code of PerAct uses a different threshold for detecting the `next_best_poses`. RK-Diffuser uses 0.01, while PerAct uses 0.1 by default (please find it [here](https://github.com/peract/peract/blob/main/helpers/demo_loading_utils.py#L21)). Please change this to 0.01 when training your PerAct model.

We do not have plans to release our checkpoints for now, but hope these answers help.

**Comment by yolo01826** [comment]
为什么没有看到训练上层策略的代码，peract用的是预训练的吗

**Comment by Flxiang1** [comment]
> hello, [@Yusufma03](https://github.com/Yusufma03). Thanks for the source code. I'm facing the some problems when reproducing training and evaluation code.
> 
> Question 1: The article says it needs to train for 100k iterations, but when I reproduced it, I found that it seemed to have converged around 1k iterations. I'm not sure if this result is normal, or if you could share the situation of your loss convergence, or could you publish the checkpoint you trained?
> 
> <img alt="image" width="1621" src="https://private-user-images.githubusercontent.com/68276188/323541014-79bcee82-90ea-4f08-bf3b-268000634e18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQwMTQ3NjcsIm5iZiI6MTc0NDAxNDQ2NywicGF0aCI6Ii82ODI3NjE4OC8zMjM1NDEwMTQtNzliY2VlODItOTBlYS00ZjA4LWJmM2ItMjY4MDAwNjM0ZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA3VDA4Mjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMGQzMTdjODBiMDBlOGNkNmY2YjBhNzZmMDVmNDI3MGZjOTI5ZGFjOGI0NWViMzA3MDVjNzljNzNlMjcxNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Dbmy1svReEWzCJLLoujiXG8qosGAZm9cK7O0bfJixU">
> Question 2: When I use my own trained checkpoint for evaluation, I find the results are poor. So, I think there was a problem during my training, but I don't know how to fix it.
> 
> <img alt="image" width="514" src="https://private-user-images.githubusercontent.com/68276188/323544057-3f765242-fb27-44b8-8938-740cf6de9b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQwMTQ3NjcsIm5iZiI6MTc0NDAxNDQ2NywicGF0aCI6Ii82ODI3NjE4OC8zMjM1NDQwNTctM2Y3NjUyNDItZmIyNy00NGI4LTg5MzgtNzQwY2Y2ZGU5YjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA3VDA4Mjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZmFjODBmZjViMzZiNjM5M2U1NjVkZDk0MGFmN2E2YjE3OWE3ZWRiNGJjYjY1ZTIzMzNhNWViNjI4OGY1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LmNFr_Q47U5EBeBrIUHPB5ulA7LjdrQZ7ofqGShr9WA"> <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/68276188/323543931-907b9636-969b-473f-9c7f-11d14829134e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQwMTQ3NjcsIm5iZiI6MTc0NDAxNDQ2NywicGF0aCI6Ii82ODI3NjE4OC8zMjM1NDM5MzEtOTA3Yjk2MzYtOTY5Yi00NzNmLTljN2YtMTFkMTQ4MjkxMzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA3VDA4Mjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMDAzMTY4NDE1ODFmNzI4ZTAyZWFiMjkwZmNiNzk1OTNkMjliOTczNjZkNzk1OTUxNGUwMDQwMTE0NDA3ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KFFgdyIu78icr7eIvsnKVekszdT6DzSGKbx3m0IcdUA">

Hello, as I have just started working on replication projects, I would like to ask how I can train my Peract checkpoint

**Comment by Flxiang1** [comment]
> hello, [@Yusufma03](https://github.com/Yusufma03). Thanks for the source code. I'm facing the some problems when reproducing training and evaluation code.
> 
> Question 1: The article says it needs to train for 100k iterations, but when I reproduced it, I found that it seemed to have converged around 1k iterations. I'm not sure if this result is normal, or if you could share the situation of your loss convergence, or could you publish the checkpoint you trained?
> 
> <img alt="image" width="1621" src="https://private-user-images.githubusercontent.com/68276188/323541014-79bcee82-90ea-4f08-bf3b-268000634e18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY4NjQzNTQsIm5iZiI6MTc0Njg2NDA1NCwicGF0aCI6Ii82ODI3NjE4OC8zMjM1NDEwMTQtNzliY2VlODItOTBlYS00ZjA4LWJmM2ItMjY4MDAwNjM0ZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTEwVDA4MDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYmY2MGNhOGFlMjQ4ZDA4ZTI3ZDAwMjVkNjg1ZmM5YTIwZDdhNGFkZGUwYzMzYjA1MzJiMzNlYmEyZmEyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r-h52J9owdg9xpyKUuSDZaQTp0NjpdtajFba-bC9TpY">
> Question 2: When I use my own trained checkpoint for evaluation, I find the results are poor. So, I think there was a problem during my training, but I don't know how to fix it.
> 
> <img alt="image" width="514" src="https://private-user-images.githubusercontent.com/68276188/323544057-3f765242-fb27-44b8-8938-740cf6de9b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY4NjQzNTQsIm5iZiI6MTc0Njg2NDA1NCwicGF0aCI6Ii82ODI3NjE4OC8zMjM1NDQwNTctM2Y3NjUyNDItZmIyNy00NGI4LTg5MzgtNzQwY2Y2ZGU5YjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTEwVDA4MDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTMzYjAzMWNkNmU3MmQwOWJhOTRiODA0ODZmOTYzM2EwMDAzOTY1MjJiZjM2MDMwNzJiNzE1OGYzMjY4NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ETVrSvgZDcnfLKOuu00npl8GF1ozkeZTiQAs8D9lq6g"> <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/68276188/323543931-907b9636-969b-473f-9c7f-11d14829134e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY4NjQzNTQsIm5iZiI6MTc0Njg2NDA1NCwicGF0aCI6Ii82ODI3NjE4OC8zMjM1NDM5MzEtOTA3Yjk2MzYtOTY5Yi00NzNmLTljN2YtMTFkMTQ4MjkxMzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTEwVDA4MDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZGE4NDg5MzFhOGY4ZDI0NDkyZjEyNTJkZjg2OWM0NzZmODk5MDEzMzI4M2M4MmVhNjljMWVmZTk1YzBjNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TE0OR5gSD7EUwyK32WGmZEvQPRz1iHoJGCdRHBoZBLU">

Hi @yuerbujin  I would like to know if you have successfully reproduced the results of the paper. Can you provide some guidance and suggestions? I would be extremely grateful
