### ISSUE TITLE
Can not run the evaluation code due to missing of PerAct checkpoint

### ISSUE THREAD

**Issue by andvg3** [dyson-ai/hdp#6]
Hi authors,

I am trying to run the evaluation code using your instruction:

`python eval.py rlbench.tasks="[<your task>]" rlbench.headless=False method.model_path=<path to rk-diffuser ckpt> framework.logdir=<path to peract ckpt dir>
`

As my guessing, `<path to rk-diffuser ckpt>` refers to the checkpoint of the RK-Diffuser model, which locates in the `snapshots` folder and `<path to peract ckpt dir>` refers to the checkpoint in the [PerAct](https://github.com/peract/peract?tab=readme-ov-file#download). Nevertheless, it seemed not working and I encoutered the following error:

> Error executing job with overrides: ['rlbench.tasks=[reach_target]', 'rlbench.headless=False', 'method.model_path=snapshots/low_level/reach_target/2024-08-28_17:36:56/model_10000.pt', 'framework.logdir=saved_models/ckpts/multi/PERACT_BC/seed5']
Traceback (most recent call last):
  File "/home/XXX/hdp/eval.py", line 253, in main
    raise Exception("Missing seed%d/config.yaml" % start_seed)
Exception: Missing seed0/config.yaml
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Of course, I have double checked to ensure the `train_config_path` exists as a relative path. I also tried to change to absolute path but still, it did not work.

I hope you can help me with this issue. Thank you very much in advance!

Best regards,
An Vuong

**Comment by andvg3** [comment]
Oh, never mind, just change the relative path to the absolute path works for me.

**Comment by Flxiang1** [comment]
> Hi authors,
> 
> I am trying to run the evaluation code using your instruction:
> 
> `python eval.py rlbench.tasks="[<your task>]" rlbench.headless=False method.model_path=<path to rk-diffuser ckpt> framework.logdir=<path to peract ckpt dir> `
> 
> As my guessing, `<path to rk-diffuser ckpt>` refers to the checkpoint of the RK-Diffuser model, which locates in the `snapshots` folder and `<path to peract ckpt dir>` refers to the checkpoint in the [PerAct](https://github.com/peract/peract?tab=readme-ov-file#download). Nevertheless, it seemed not working and I encoutered the following error:
> 
> > Error executing job with overrides: ['rlbench.tasks=[reach_target]', 'rlbench.headless=False', 'method.model_path=snapshots/low_level/reach_target/2024-08-28_17:36:56/model_10000.pt', 'framework.logdir=saved_models/ckpts/multi/PERACT_BC/seed5']
> > Traceback (most recent call last):
> > File "/home/XXX/hdp/eval.py", line 253, in main
> > raise Exception("Missing seed%d/config.yaml" % start_seed)
> > Exception: Missing seed0/config.yaml
> > Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> 
> Of course, I have double checked to ensure the `train_config_path` exists as a relative path. I also tried to change to absolute path but still, it did not work.
> 
> I hope you can help me with this issue. Thank you very much in advance!
> 
> Best regards, An Vuong

Hello, as I have just started working on replication projects, I would like to ask how I can train my Peract checkpoint
