### ISSUE TITLE
Cannot reproduce the result

### ISSUE THREAD

**Issue by benlam62** [dyson-ai/hdp#8]
Hi @Yusufma03,  I trained the HDP model for the RLBench task Open Drawer with all 3 variations but all 10 eval tasks score 0. I notice that the robot arm could reach the right level of the top, middle and bottom drawer but fail to grasp the handle to pull the drawer out.  Can someone suggest what went wrong? Below is the training details:

- A pre-trained multi-task Peract agent from the [official Peract page](https://github.com/peract/peract) which trained with 100 demos per task (18 tasks in total). [Checkpoint download](https://github.com/peract/peract/releases/download/v1.0.0/peract_600k.zip). 
- 120 training demos (40 demos per variation), 60 evaluation demos (20 demos per variation)
- 100,000 training episodes

**Comment by Yusufma03** [comment]
Hi Ben, thanks for your interest in our work. Note that you will need to train your own peract as HDP and PerAct are using different `stopping_delta` during key frame discovery. HDP is using 0.01 (check [here](https://github.com/dyson-ai/hdp/blob/main/rk_diffuser/dataset/rl_bench_dataset.py#L333)) and PerAct is using 0.1 (check [here](https://github.com/peract/peract/blob/main/agents/peract_bc/launch_utils.py#L251)). Please train PerAct using 0.01. Besides, as diffusion policies are bad at generalization, you will also need to enable data augmentation by setting `demo_aug_ratio > 0` (check [here](https://github.com/dyson-ai/hdp/blob/main/cfgs/env/sim.yaml#L11))

**Comment by benlam62** [comment]
Thanks. What would be the demo_aug_ratio to start with and the increment to
be applied?

在 2024年11月2日週六 10:35，Xiao Ma ***@***.***> 寫道：

**Comment by Flxiang1** [comment]
> Hi [@Yusufma03](https://github.com/Yusufma03), I trained the HDP model for the RLBench task Open Drawer with all 3 variations but all 10 eval tasks score 0. I notice that the robot arm could reach the right level of the top, middle and bottom drawer but fail to grasp the handle to pull the drawer out. Can someone suggest what went wrong? Below is the training details:
> 
> * A pre-trained multi-task Peract agent from the [official Peract page](https://github.com/peract/peract) which trained with 100 demos per task (18 tasks in total). [Checkpoint download](https://github.com/peract/peract/releases/download/v1.0.0/peract_600k.zip).
> * 120 training demos (40 demos per variation), 60 evaluation demos (20 demos per variation)
> * 100,000 training episodes

Hello, as I have just started working on replication projects, I would like to ask how I can train my Peract checkpoint

**Comment by Flxiang1** [comment]
> Hi [@Yusufma03](https://github.com/Yusufma03), I trained the HDP model for the RLBench task Open Drawer with all 3 variations but all 10 eval tasks score 0. I notice that the robot arm could reach the right level of the top, middle and bottom drawer but fail to grasp the handle to pull the drawer out. Can someone suggest what went wrong? Below is the training details:
> 
> * A pre-trained multi-task Peract agent from the [official Peract page](https://github.com/peract/peract) which trained with 100 demos per task (18 tasks in total). [Checkpoint download](https://github.com/peract/peract/releases/download/v1.0.0/peract_600k.zip).
> * 120 training demos (40 demos per variation), 60 evaluation demos (20 demos per variation)
> * 100,000 training episodes

Hi @benlam62  I would like to know if you have successfully reproduced the results of the paper. Can you provide some guidance and suggestions? I would be extremely grateful
